# Generated by Erlang.mk. Edit at your own risk!

src/container.erl:: src/common_macros.hrl; @touch $@
src/lib_service.erl:: src/common_macros.hrl; @touch $@
src/misc_lib.erl:: src/common_macros.hrl; @touch $@
src/stug_service.erl:: src/common_macros.hrl; @touch $@
src/tcp_client.erl:: src/common_macros.hrl; @touch $@

COMPILE_FIRST +=
